### PR TITLE
DoRun: fix possible invalid read

### PR DESCRIPTION
**Pull request by starius**
If a string passed to `DoRun` is less than `sizeof(size_t)`, then its content
can't be read as if its type is `size_t*`. `DoRun` splits the string to 3
parts: pre-aligned, aligned and post-aligned. If there is no aligned part
of a string, then whole string is treated as pre- and post-aligned.

The error was caused by casting pre- and post-aligned parts to `size_t*`.
Now they are processed by code operating on `char*` (function `SafeRunChunk`).
(Actually pre-aligned part is allowed to be casted to `size_t*`, if aligned
part exists, ie. length of the string > `size(size_t)`.)

Target strings:
 * length <= 6 - error
 * length >= 7 - no error

String of length 7 fits in size_t (+1 byte for terminating '\0'). 

Valgrind output before this patch applied:
```
==26448== Invalid read of size 8                                                                      
==26448==    at 0x60439F5: void Pire::Impl::DoRun<Pire::Impl::Scanner<Pire::Impl::Relocatable, Pire::Impl::ExitMasks<2ul> >, Pire::Impl::RunPred<Pire::Impl::Scanner<Pire::Impl::Relocatable, Pire::Impl::ExitMasks<2ul> > > >(Pire::Impl::Scanner<Pire::Impl::Relocatable, Pire::Impl::ExitMasks<2ul> > const&, Pire::Impl::Scanner<Pire::Impl::Relocatable, Pire::Impl::ExitMasks<2ul> >::State&, char const*, char const*, Pire::Impl::RunPred<Pire::Impl::Scanner<Pire::Impl::Relocatable, Pire::Impl::ExitMasks<2ul> > >) (run.h:129)                                                                                          
==26448==    by 0x603C906: void Pire::Run<Pire::Impl::Scanner<Pire::Impl::Relocatable, Pire::Impl::ExitMasks<2ul> > >(Pire::Impl::Scanner<Pire::Impl::Relocatable, Pire::Impl::ExitMasks<2ul> > const&, Pire::Impl::Scanner<Pire::Impl::Relocatable, Pire::Impl::ExitMasks<2ul> >::State&, char const*, char const*) (run.h:266)
==26448==    by 0x60438C6: Pire::RunHelper<Pire::Impl::Scanner<Pire::Impl::Relocatable, Pire::Impl::ExitMasks<2ul> > >::Run(char const*, char const*) (run.h:341)                                           
==26448==    by 0x603C899: Pire::RunHelper<Pire::Impl::Scanner<Pire::Impl::Relocatable, Pire::Impl::ExitMasks<2ul> > >::Run(char const*, unsigned long) (run.h:342) 
```
Applying this patch the valgrind error was fixed.

### CODE REVIEW

**Comment by dprokoptsev** [comment]
No thank you. Reading pre/post-aligned parts of input strings as one size_t has been there for a reason, is perfectly safe and thus should stay there.

There's no way to keep Pire at its current performance level and make paranoid Valgrind happy, hence code branches under PIRE_ENABLE_VALGRIND_SAFE macro which you've deleted.

Please try to reproduce the possible bug with the macro enabled.

**Comment by sergey-v-galtsev** [comment]
> Reading pre/post-aligned parts of input strings as one size_t has been there for a reason, is perfectly safe and thus should stay there.

Well, this is untrue.
[Memory segmentation](https://en.wikipedia.org/wiki/Memory_segmentation) in IA32 allows to create a byte-granular segment of memory. Effectively making particular byte accessible while keeping corresponding word inaccessible as a whole.

**Comment by dprokoptsev** [comment]
Let's be realistic, nobody's using segmentation these days (I would also add the same about IA32 as the whole, but nevertheless).

Keep in mind that the patch being discussed presumably introduces 2x slowdown on short strings. Unacceptable tradeoff, if you ask me.

**Comment by sergey-v-galtsev** [comment]
> Keep in mind that the patch being discussed presumably introduces 2x slowdown on short strings. Unacceptable tradeoff, if you ask me.

I agree that the slowdown is unacceptable.
I'm just emphasizing that *program correctness* is traded for speed here.

**Pull request closed without merging**
